name = "CompasToolkit"
uuid = "7e3df991-ca6f-4721-8d7b-832e42ca037e"
authors = ["S Heldens", "A Sclocco", "O van der Heide"]
version = "0.1.0"

[deps]
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
